[package]
name = "pipoquinha"
version = "0.1.0"
authors = ["Celso Bonutti Filho <i.am@cel.so>", "Danilo Fragoso <danilo@fragoso.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pom = "3.2.0"